### ISSUE TITLE
Suggestion: Prevent `Delete packages ...` if extract folder is used

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/UnrenGUI#5]
When you choose to have the tool create an `extracted` folder, deleting rpa files will lead to errors. 
Maybe better to disable the `Delete packages after extracting` checkbox if the `Create folder for extracted files` checkbox is ticked

**Comment by littleraisins** [comment]
Skipped this one because it limits functionality and no data is lost, you can move/copy extracted files back to game folder.
Everything else was implemented in the version 0.5.0
